name: Release

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  directories-matrix:
    uses: ./.github/workflows/release_directory.js.yml 
    with:
      directory: ${{ matrix.directory }}
    secrets: inherit
    strategy:
      # super important if you want to see all results, even if one fails
      # fail-fast is true by default
      fail-fast: false
      matrix:
        directory: ["app", "server"] 
